name: Deploy pr preview

on:
  pull_request:
    types:
      - opened
      - synchronize
      - closed
    paths:
      - "docs/sources/**"

jobs:
    if: "!github.event.pull_request.head.repo.fork"
    uses: grafana/writers-toolkit/.github/workflows/deploy-preview.yml@jdb/deploy-preview
    with:
      branch: ${{ github.head_ref }}
      event_number: ${{ github.event.number }}
      repo: mimir
      sha: ${{ github.event.pull_request.head.sha }}
      sources: |
        [
          {
            "index_file": true,
            "relative_prefix": "/docs/mimir/latest/",
            "repo": mimir",
            "source_directory": "docs/sources/mimir",
            "website_directory": "content/docs/mimir/latest"
          },
          {
            "index_file": true,
            "relative_prefix": "/docs/helm-charts/mimir-distributed/latest/",
            "repo": mimir",
            "source_directory": "docs/sources/mimir-distributed",
            "website_directory": "content/docs/helm-charts/mimir-distributed/latest"
          }
        ]
